name: Publish Artifacts

on: workflow_dispatch

permissions:
  contents: read

env:
  ORG_GRADLE_PROJECT_mavenCentralUsername: '${{ secrets.MAVEN_CENTRAL_USERNAME }}'
  ORG_GRADLE_PROJECT_mavenCentralPassword: '${{ secrets.MAVEN_CENTRAL_PASSWORD }}'
  ORG_GRADLE_PROJECT_signingInMemoryKeyId: '${{ secrets.SIGNING_KEY_ID }}'
  ORG_GRADLE_PROJECT_signingInMemoryKey: '${{ secrets.SIGNING_KEY }}'
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: '${{ secrets.SIGNING_KEY_PASSWORD }}'

jobs:
  build:
    uses: ./.github/workflows/gradle.yml
  deploy:
    needs: build
    strategy:
      matrix:
        include:
          - target: publishIosArm64PublicationToMavenCentral
            os: macos-latest
          - target: publishAndroidReleasePublicationToMavenCentral
            os: ubuntu-latest
          - target: publishJvmPublicationToMavenCentral
            os: ubuntu-latest
          - target: publishLinuxX64PublicationToMavenCentral
            os: ubuntu-latest
          - target: publishKotlinMultiplatformPublicationToMavenCentral
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - uses: actions/cache@v3
        with:
          path: |
            ~/.konan
          key: ${{ runner.os }}-${{ hashFiles('**/.lock') }}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish to Maven Central
        run: ./gradlew publishAllPublicationsToMavenCentralRepository --no-configuration-cache